# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d705f0b646feddde696ba0b33ae6947c76e80a4339dff2508dbfb3b1679a81c2be57c388abce608c04cd2d46874510c2bd7ef604481a348565812fa942e8a83

test:
  secret_key_base: 4e31752b6ca790b16558bc091a0fffb8e90c957e4a02f67e674b780c8fca645d79d072a86e8071b7ad01b6699bd8116fb141fee5afcbf5154a4478779739dbae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
